/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "تحديد عنصر واجهة مستخدم الخريطة",
        settings: "الإعدادات",
        showScale: "Scale Show",
        showZoom: "Show Zoom",
        uiPictometryConfiguration: "Pictometry Configuration",
        uiPictometryBaseUrl: "قاعدة القياس",
        uiEnterTheFullUrlIncludingAspx: "أدخل الملف الكامل",
        uiButtonVisibility: "Button Visibility",
        uiHelp: "المساعدة",
        uiShowHelpGuide: "دليل المساعدة",
        uiShowTheQuestionMarkButtonThat: "اظهر زر التساؤل الذي يفتح المرشد",
        showPictometryButton: "نري \"بوتون\"",
        showGoogleStreetViewButton: "Show Google Street View Button",
        showGoogleMaps3dButton: "Show Google Maps 3D Button",
        showBingSatelliteButton: "ساتل Bing Button",
        showBingStreetsideButton: "عرض شارع \"بينج\"",
        showCopyCoordinatesButton: "(أظهروا منسقي (بوتون"
      })
    }
  }
})
