/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Избиране на изпълним модул за карта",
        settings: "Настройки",
        showScale: "Показване на скалата",
        showZoom: "Показване на увеличение",
        uiPictometryConfiguration: "Настройване на пиктометрията",
        uiPictometryBaseUrl: "Адрес на пиктометрията",
        uiEnterTheFullUrlIncludingAspx: "Въведете пълния адрес, включително .aspx файл",
        uiButtonVisibility: "Видимост на бутоните",
        uiHelp: "Помощ",
        uiShowHelpGuide: "Показване на ръководство за помощ",
        uiShowTheQuestionMarkButtonThat: "Показване на бутона въпрос-марка, която отваря джаджа помощ ръководство",
        showPictometryButton: "Показване на бутон за пиктометрия",
        showGoogleStreetViewButton: "Показване на бутон на Google Street",
        showGoogleMaps3dButton: "Показване на Google карти 3D бутон",
        showBingSatelliteButton: "Показване на сателитен бутон Bing",
        showBingStreetsideButton: "Показване на бутон Bing Streetside",
        showCopyCoordinatesButton: "Показване на координатите"
      })
    }
  }
})
