/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Vybrat widget mapy",
        settings: "Nastavení",
        showScale: "Zobrazit měřítko",
        showZoom: "Zobrazit zoom",
        uiPictometryConfiguration: "Nastavení piktometrie",
        uiPictometryBaseUrl: "Name",
        uiEnterTheFullUrlIncludingAspx: "Zadejte plnou URL včetně .aspx souboru",
        uiButtonVisibility: "Viditelnost tlačítka",
        uiHelp: "Nápověda",
        uiShowHelpGuide: "Zobrazit nápovědu",
        uiShowTheQuestionMarkButtonThat: "Zobrazit tlačítko question- mark, které otevře nápovědu widget",
        showPictometryButton: "Zobrazit tlačítko Pictometrie",
        showGoogleStreetViewButton: "Zobrazit tlačítko Google Street View",
        showGoogleMaps3dButton: "Zobrazit tlačítko Google Maps 3D",
        showBingSatelliteButton: "Zobrazit Bing Satellite Button",
        showBingStreetsideButton: "Zobrazit tlačítko Bing Streetside",
        showCopyCoordinatesButton: "Zobrazit tlačítko Kopírovat souřadnice"
      })
    }
  }
})
