/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Επιλογή widget χάρτη",
        settings: "Ρυθμίσεις",
        showScale: "Εμφάνιση κλίμακας",
        showZoom: "Εμφάνιση εστίασης",
        uiPictometryConfiguration: "Configuration εικονομετρίας",
        uiPictometryBaseUrl: "Βασικό URL εικονομετρίας",
        uiEnterTheFullUrlIncludingAspx: "Εισάγετε το πλήρες URL συμπεριλαμβανομένου του αρχείου .aspx",
        uiButtonVisibility: "Ορατότητα κουμπιού",
        uiHelp: "Βοήθεια",
        uiShowHelpGuide: "Εμφάνιση οδηγού βοήθειας",
        uiShowTheQuestionMarkButtonThat: "Εμφάνιση του κουμπιού ερωτηματολογίου που ανοίγει τον οδηγό βοήθειας widget",
        showPictometryButton: "Εμφάνιση κουμπιού εικονομετρίας",
        showGoogleStreetViewButton: "Εμφάνιση κουμπιού προβολής οδών Google",
        showGoogleMaps3dButton: "Εμφάνιση χαρτών 3D Google",
        showBingSatelliteButton: "Εμφάνιση κουμπιού δορυφόρου Bing",
        showBingStreetsideButton: "Εμφάνιση κουμπιού Bing Streetside",
        showCopyCoordinatesButton: "Εμφάνιση κουμπιού συντεταγμένων αντιγραφής"
      })
    }
  }
})
