/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Seleccionar widget Mapa",
        settings: "Configuración",
        showScale: "Mostrar escala",
        showZoom: "Mostrar Zoom",
        uiPictometryConfiguration: "Configuración de Pictometría",
        uiPictometryBaseUrl: "Base de Pictometría URL",
        uiEnterTheFullUrlIncludingAspx: "Introduzca la URL completa incluyendo el archivo .aspx",
        uiButtonVisibility: "Button Visibilidad",
        uiHelp: "Ayuda",
        uiShowHelpGuide: "Mostrar guía de ayuda",
        uiShowTheQuestionMarkButtonThat: "Mostrar el botón de la marca de preguntas que abre el widget guía de ayuda",
        showPictometryButton: "Mostrar Pictometría Button",
        showGoogleStreetViewButton: "Mostrar Google Street View Button",
        showGoogleMaps3dButton: "Mostrar Google Maps 3D Button",
        showBingSatelliteButton: "Mostrar Bing Satellite Button",
        showBingStreetsideButton: "Mostrar Bing Streetside Button",
        showCopyCoordinatesButton: "Mostrar Copia Coordenadas Button"
      })
    }
  }
})
