/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Vali kaardividin",
        settings: "Seaded",
        showScale: "Skaala näitamine",
        showZoom: "Näita suurendust",
        uiPictometryConfiguration: "Piktomeetria seadistamine",
        uiPictometryBaseUrl: "Piktomeetria baasi URL",
        uiEnterTheFullUrlIncludingAspx: "Sisesta täielik URL, sealhulgas .aspx- fail",
        uiButtonVisibility: "Nuppude nähtavus",
        uiHelp: "Abi",
        uiShowHelpGuide: "Abijuhendi näitamine",
        uiShowTheQuestionMarkButtonThat: "Küsimusemärgi nupu näitamine, mis avab vidina abi juhendi",
        showPictometryButton: "Piktomeetri nupu näitamine",
        showGoogleStreetViewButton: "Google Street View nupu näitamine",
        showGoogleMaps3dButton: "Google Maps 3D nupu näitamine",
        showBingSatelliteButton: "Bingi satelliidinupu näitamine",
        showBingStreetsideButton: "Bing Streetside' i nupu näitamine",
        showCopyCoordinatesButton: "Kopeeri koordinaatide nupp"
      })
    }
  }
})
