/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Valitse kartan pienoisohjelma",
        settings: "Asetukset",
        showScale: "Näytä vaaka",
        showZoom: "Näytä suurennos",
        uiPictometryConfiguration: "Piktometrian asetukset",
        uiPictometryBaseUrl: "Piktometrian perusverkko- osoite",
        uiEnterTheFullUrlIncludingAspx: "Anna koko URL-osoite, mukaan lukien .aspx-tiedosto",
        uiButtonVisibility: "Napin näkyvyys",
        uiHelp: "Ohje",
        uiShowHelpGuide: "Näytä ohje",
        uiShowTheQuestionMarkButtonThat: "Näytä kysymys-merkki-painike, joka avaa widget ohjeen"
      })
    }
  }
})
