/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "בחר ווידג'ט מפה",
        settings: "הגדרות",
        showScale: "Show Scale",
        showZoom: "הצג ZOOS",
        uiPictometryConfiguration: "המונחים: Pictometry Configuration",
        uiPictometryBaseUrl: "בסיס פיקניק",
        uiEnterTheFullUrlIncludingAspx: "היכנס ל-URL המלא כולל קובץ .aspx",
        uiButtonVisibility: "Button Visibility",
        uiHelp: "עזרה",
        uiShowHelpGuide: "מדריך עזרה",
        uiShowTheQuestionMarkButtonThat: "הצג את לחצן סימן שאלה פותח את מדריך העזרה widget"
      })
    }
  }
})
