/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Térképwidget kiválasztása",
        settings: "Beállítások",
        showScale: "Méret megjelenítése",
        showZoom: "Nagyítás megjelenítése",
        uiPictometryConfiguration: "Piktometriai beállítás",
        uiPictometryBaseUrl: "Piktometriai alapURL",
        uiEnterTheFullUrlIncludingAspx: "Adja meg a teljes URL-t, beleértve a .aspx fájlt",
        uiButtonVisibility: "A gomb láthatósága",
        uiHelp: "Súgó",
        uiShowHelpGuide: "Segítőútmutató megjelenítése",
        uiShowTheQuestionMarkButtonThat: "Megjeleníti a kérdőjel gombot, amely megnyitja a widget súgó útmutatót"
      })
    }
  }
})
