/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Pilih widget peta",
        settings: "Pengaturan",
        showScale: "Tampilkan Skala",
        showZoom: "Tampilkan pembesaran",
        uiPictometryConfiguration: "Konfigurasi Pictometri",
        uiPictometryBaseUrl: "URL Basis Pictometri",
        uiEnterTheFullUrlIncludingAspx: "Masukkan URL lengkap termasuk berkas .aspx",
        uiButtonVisibility: "Visibilitas Tombol",
        uiHelp: "Bantuan",
        uiShowHelpGuide: "Tampilkan panduan bantuan",
        uiShowTheQuestionMarkButtonThat: "Tampilkan tombol tanya-tandai yang membuka panduan bantuan widget",
        showPictometryButton: "Tampilkan Tombol Fotometri",
        showGoogleStreetViewButton: "Tampilkan Tombol Tampilan Jalan Google",
        showGoogleMaps3dButton: "Tampilkan Tombol 3D Peta Google",
        showBingSatelliteButton: "Tampilkan Tombol Satelit Bing",
        showBingStreetsideButton: "Tampilkan Tombol Sisi Jalanan Bing",
        showCopyCoordinatesButton: "Tampilkan Tombol Koordinat Salinan"
      })
    }
  }
})
