/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Selezione widget mappa",
        settings: "Impostazioni",
        showScale: "Mostra la scala",
        showZoom: "Mostra Zoom",
        uiPictometryConfiguration: "Configurazione di pittometria",
        uiPictometryBaseUrl: "URL della base di pittometria",
        uiEnterTheFullUrlIncludingAspx: "Inserisci l'URL completo compreso il file .aspx",
        uiButtonVisibility: "Visibilità del pulsante",
        uiHelp: "Guida",
        uiShowHelpGuide: "Mostra la guida",
        uiShowTheQuestionMarkButtonThat: "Mostra il pulsante di punto interrogativo che apre la guida di aiuto widget",
        showPictometryButton: "Mostra pulsante Pictometry",
        showGoogleStreetViewButton: "Mostra Google Street View Pulsante",
        showGoogleMaps3dButton: "Mostra Google Maps 3D Button",
        showBingSatelliteButton: "Mostra pulsante satellitare Bing",
        showBingStreetsideButton: "Visualizza pulsante Bing Streetside",
        showCopyCoordinatesButton: "Show Copy Coordinas Pulsante"
      })
    }
  }
})
