/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "マップ ウィジェットの選択",
        settings: "設定",
        showScale: "ショースケール",
        showZoom: "ズームショー",
        uiPictometryConfiguration: "ピクトメトリー構成",
        uiPictometryBaseUrl: "ピクトメトリーベースURL",
        uiEnterTheFullUrlIncludingAspx: ".aspxファイルを含むフルURLを入力してください",
        uiButtonVisibility: "ボタンの可視性",
        uiHelp: "ヘルプ",
        uiShowHelpGuide: "ヘルプガイドを表示",
        uiShowTheQuestionMarkButtonThat: "ウィジェットヘルプガイドを開く質問のボタンを表示する"
      })
    }
  }
})
