/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Pasirinkti žemėlapio valdiklį",
        settings: "Nustatymai",
        showScale: "Rodyti skalę",
        showZoom: "Rodyti mastelį",
        uiPictometryConfiguration: "Piktometrijos konfigūracija",
        uiPictometryBaseUrl: "Piktometrijos pagrindinis URL",
        uiEnterTheFullUrlIncludingAspx: "Įveskite visą URL, įskaitant .aspx failą",
        uiButtonVisibility: "Mygtuko matomumas",
        uiHelp: "Pagalba",
        uiShowHelpGuide: "Rodyti pagalbos vadovą",
        uiShowTheQuestionMarkButtonThat: "Rodyti klausimų žymėjimo mygtuką, kuris atveria valdikliui skirtą pagalbos vadovą",
        showPictometryButton: "Rodyti piktometrijos mygtuką",
        showGoogleStreetViewButton: "Rodyti Google gatvės peržiūros mygtuką",
        showGoogleMaps3dButton: "Rodyti \"Google\" žemėlapių 3D mygtuką",
        showBingSatelliteButton: "Rodyti Bing Satellite mygtuką",
        showBingStreetsideButton: "Rodyti Bing Streetside mygtuką",
        showCopyCoordinatesButton: "Rodyti aplanko koordinates"
      })
    }
  }
})
