/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Atlasīt kartes logrīku",
        settings: "Iestatījumi",
        showScale: "Rādīt mērogojumu",
        showZoom: "Rādīt izmēru",
        uiPictometryConfiguration: "Piktometrijas konfigurācija",
        uiPictometryBaseUrl: "Piktometrijas bāzes URL",
        uiEnterTheFullUrlIncludingAspx: "Ievadiet pilnu URL, ieskaitot .aspx failu",
        uiButtonVisibility: "Pogu redzamība",
        uiHelp: "Palīdzība",
        uiShowHelpGuide: "Rādīt palīdzības ceļvedi",
        uiShowTheQuestionMarkButtonThat: "Rādīt jautājumu zīmes pogu, kas atver logdaļu palīdzības rokasgrāmatu"
      })
    }
  }
})
