/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Kaartwidget selecteren",
        settings: "Instellingen",
        showScale: "Schaal tonen",
        showZoom: "Zoomen",
        uiPictometryConfiguration: "Pictometrieconfiguratie",
        uiPictometryBaseUrl: "Pictometrie basis-URL",
        uiEnterTheFullUrlIncludingAspx: "Voer de volledige URL in inclusief .aspx-bestand",
        uiButtonVisibility: "Knop zichtbaar",
        uiHelp: "Hulp",
        uiShowHelpGuide: "Hulplijn tonen",
        uiShowTheQuestionMarkButtonThat: "De knop met het vraagteken tonen die de hulplijn widget opent"
      })
    }
  }
})
