/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Velg kartminiprogram",
        settings: "Innstillinger",
        showScale: "Vis skala",
        showZoom: "Vis zoom",
        uiPictometryConfiguration: "Konfigurasjon av piktometri",
        uiPictometryBaseUrl: "Pictometry Base URL",
        uiEnterTheFullUrlIncludingAspx: "Skriv inn hele URL inkludert .aspx-fil",
        uiButtonVisibility: "Synlighet av knapp",
        uiHelp: "Hjelp",
        uiShowHelpGuide: "Vis hjelpguide",
        uiShowTheQuestionMarkButtonThat: "Vis spørsmålsmerkeknappen som åpner widget-hjelpeguiden",
        showPictometryButton: "Vis Pictometry knapp",
        showGoogleStreetViewButton: "Vis Google Street View-knappen",
        showGoogleMaps3dButton: "Vis Google Maps 3D-knapp",
        showBingSatelliteButton: "Vis Bing Satellittknapp",
        showBingStreetsideButton: "Vis Bing Streetside-knappen",
        showCopyCoordinatesButton: "Vis kopikoordinatknapp"
      })
    }
  }
})
