/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Wybierz widżet mapy",
        settings: "Parametry",
        showScale: "Pokaż skalę",
        showZoom: "Pokaż powiększenie",
        uiPictometryConfiguration: "Konfiguracja piktometrii",
        uiPictometryBaseUrl: "Piktometry Base URL",
        uiEnterTheFullUrlIncludingAspx: "Wprowadź pełny adres URL w tym plik .aspx",
        uiButtonVisibility: "Widoczność przycisku",
        uiHelp: "Pomoc",
        uiShowHelpGuide: "Pokaż przewodnik pomocy",
        uiShowTheQuestionMarkButtonThat: "Pokaż przycisk question- mark, który otwiera przewodnik pomocy widget"
      })
    }
  }
})
