/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Selecionar widget de mapa",
        settings: "Definições",
        showScale: "Mostrar a Escala",
        showZoom: "Mostrar Ampliação",
        uiPictometryConfiguration: "Configuração da Pictometria",
        uiPictometryBaseUrl: "URL base de pictometria",
        uiEnterTheFullUrlIncludingAspx: "Digite o URL completo incluindo arquivo .aspx",
        uiButtonVisibility: "Visibilidade do Botão",
        uiHelp: "Ajuda",
        uiShowHelpGuide: "Mostrar guia de ajuda",
        uiShowTheQuestionMarkButtonThat: "Mostrar o botão de marca de perguntas que abre o guia de ajuda do elemento",
        showPictometryButton: "Mostrar o Botão de Pictometria",
        showGoogleStreetViewButton: "Mostrar o botão do Google Street View",
        showGoogleMaps3dButton: "Mostrar o Botão 3D do Google Maps",
        showBingSatelliteButton: "Mostrar o Botão de Satélite do Bing",
        showBingStreetsideButton: "Mostrar o botão Bing Streetside",
        showCopyCoordinatesButton: "Mostrar o Botão Copiar as Coordenadas"
      })
    }
  }
})
