/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Selectare widget de hartă",
        settings: "Setări",
        showScale: "Afișează scala",
        showZoom: "Arată zoom",
        uiPictometryConfiguration: "Configurare pictometrie",
        uiPictometryBaseUrl: "Name",
        uiEnterTheFullUrlIncludingAspx: "Introduceți URL- ul complet, inclusiv fișierul .aspx",
        uiButtonVisibility: "Vizibilitate buton",
        uiHelp: "Ajutor",
        uiShowHelpGuide: "Arată ghidul de ajutor",
        uiShowTheQuestionMarkButtonThat: "Arată butonul semn de întrebare care deschide ghidul de ajutor widget",
        showPictometryButton: "Arată butonul de pictometrie",
        showGoogleStreetViewButton: "Arată butonul Google Street View",
        showGoogleMaps3dButton: "Arată harta Google butonul 3D",
        showBingSatelliteButton: "Arată butonul din satelit Bing",
        showBingStreetsideButton: "Arată butonul Bing Streetside",
        showCopyCoordinatesButton: "Arată coordonatele de copiere buton"
      })
    }
  }
})
