/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Выбрать виджет карты",
        settings: "Настройки",
        showScale: "Шкала шоу",
        showZoom: "Показать Zoom",
        uiPictometryConfiguration: "Конфигурация пиктометрии",
        uiPictometryBaseUrl: "Пиктометрическая база URL",
        uiEnterTheFullUrlIncludingAspx: "Введите полный URL, включая файл .aspx",
        uiButtonVisibility: "Кнопочная видимость",
        uiHelp: "Справка",
        uiShowHelpGuide: "Показать справочник",
        uiShowTheQuestionMarkButtonThat: "Покажите кнопку вопрос-марка, которая открывает руководство по помощи виджета",
        showPictometryButton: "Кнопка пиктометрии",
        showGoogleStreetViewButton: "Кнопка Google Street View",
        showGoogleMaps3dButton: "Показать Google Maps 3D",
        showBingSatelliteButton: "Спутниковая кнопка Bing",
        showBingStreetsideButton: "Исполнитель: Bing Streetside Button",
        showCopyCoordinatesButton: "Кнопка Координаты копирования"
      })
    }
  }
})
