/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Vybrať mapový widget",
        settings: "Nastavenia",
        showScale: "Zobraziť stupnicu",
        showZoom: "Zobraziť zoom",
        uiPictometryConfiguration: "Nastavenie piktometrie",
        uiPictometryBaseUrl: "Piktometria základná URL",
        uiEnterTheFullUrlIncludingAspx: "Zadajte celú URL vrátane súboru .aspx",
        uiButtonVisibility: "Viditeľnosť tlačidla",
        uiHelp: "Pomocník",
        uiShowHelpGuide: "Zobraziť návod na pomoc",
        uiShowTheQuestionMarkButtonThat: "Zobraziť tlačidlo otázniku, ktoré otvorí sprievodcu pomocníkom"
      })
    }
  }
})
