/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Izberi pripomoček karte",
        settings: "Nastavitve",
        showScale: "Prikaži merilo",
        showZoom: "Prikaži povečavo",
        uiPictometryConfiguration: "Nastavitev piktometrije",
        uiPictometryBaseUrl: "URL osnove za piktometrijo",
        uiEnterTheFullUrlIncludingAspx: "Vnesite celoten URL, vključno z datoteko .aspx",
        uiButtonVisibility: "Vidljivost gumbov",
        uiHelp: "Pomoč",
        uiShowHelpGuide: "Prikaži vodnik za pomoč",
        uiShowTheQuestionMarkButtonThat: "Prikaži gumb z vprašanji, ki odpre widget pomoč vodnik"
      })
    }
  }
})
