/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Izberi pripomoček karte",
        settings: "Nastavitve",
        showScale: "Show Scale",
        showZoom: "Show Zoom"
      })
    }
  }
})
