/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Izaberite vidžet za mapu",
        settings: "Podešavanja",
        showScale: "Show Scale",
        showZoom: "Show Zoom",
        uiPictometryConfiguration: "Pictometry Configuration",
        uiPictometryBaseUrl: "Pictometry Base URL",
        uiEnterTheFullUrlIncludingAspx: "Enter the full URL including .aspx file",
        uiButtonVisibility: "Button Visibility",
        uiHelp: "Pomoć",
        uiShowHelpGuide: "Show help guide",
        uiShowTheQuestionMarkButtonThat: "Show the question-mark button that opens the widget help guide",
        showPictometryButton: "Show Pictometry Button",
        showGoogleStreetViewButton: "Show Google Street View Button",
        showGoogleMaps3dButton: "Show Google Maps 3D Button",
        showBingSatelliteButton: "Show Bing Satellite Button",
        showBingStreetsideButton: "Show Bing Streetside Button",
        showCopyCoordinatesButton: "Show Copy Coordinates Button"
      })
    }
  }
})
