/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Välj kartwidget",
        settings: "Inställningar",
        showScale: "Visa skala",
        showZoom: "Visa Zoom",
        uiPictometryConfiguration: "Pictometry Configuration",
        uiPictometryBaseUrl: "Pictometry Base URL",
        uiEnterTheFullUrlIncludingAspx: "Ange hela URL inklusive .aspx-filen",
        uiButtonVisibility: "Knappsynlighet",
        uiHelp: "Hjälp",
        uiShowHelpGuide: "Visa hjälp guide",
        uiShowTheQuestionMarkButtonThat: "Visa frågemärke knappen som öppnar widget hjälp guide"
      })
    }
  }
})
