/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Harita aracı seç",
        settings: "Ayarlar",
        showScale: "Show Scale",
        showZoom: "Zoom Show",
        uiPictometryConfiguration: "Pictometry Build",
        uiPictometryBaseUrl: "Pictometry Base URL",
        uiEnterTheFullUrlIncludingAspx: ".aspx dosyası dahil tüm URL girin",
        uiButtonVisibility: "Düğme Viability",
        uiHelp: "Yardım",
        uiShowHelpGuide: "Show help guide",
        uiShowTheQuestionMarkButtonThat: "Widget'ı açan soru işaret düğmesine göster"
      })
    }
  }
})
