/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Виберіть віджет карти",
        settings: "Налаштування",
        showScale: "Показати масштаб",
        showZoom: "Показати Zoom",
        uiPictometryConfiguration: "Налаштування піктометрії",
        uiPictometryBaseUrl: "Pictometry Базовий URL",
        uiEnterTheFullUrlIncludingAspx: "Введіть повну URL-адресу, включаючи файл .aspx",
        uiButtonVisibility: "Кнопка Visibility",
        uiHelp: "Довідка",
        uiShowHelpGuide: "Показати посібник",
        uiShowTheQuestionMarkButtonThat: "Показати натис-mark, який відкриває посібник з підтримки віджету"
      })
    }
  }
})
