/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "Chọn tiện ích bản đồ",
        settings: "Thiết lập",
        showScale: "Hiện tỷ lệ",
        showZoom: "Hiện cỡ ảnh",
        uiPictometryConfiguration: "Cấu hình Hình Hình học",
        uiPictometryBaseUrl: "URL cơ số hình người",
        uiEnterTheFullUrlIncludingAspx: "Nhập địa chỉ URL đầy đủ bao gồm tập tin .aspx",
        uiButtonVisibility: "Khả năng nhìn của nút",
        uiHelp: "Trợ giúp",
        uiShowHelpGuide: "Hiện hướng dẫn trợ giúp",
        uiShowTheQuestionMarkButtonThat: "Hiển thị nút đánh dấu câu hỏi để mở hướng dẫn trợ giúp ô điều khiển",
        showPictometryButton: "Hiện nút hình ảnh",
        showGoogleStreetViewButton: "Hiện nút xem trên đường Google",
        showGoogleMaps3dButton: "Hiện nút sơ đồ 3D của Google",
        showBingSatelliteButton: "Hiện nút vệ tinh Bing",
        showBingStreetsideButton: "Hiện nút lề đường Bing",
        showCopyCoordinatesButton: "Hiện nút Sao chép"
      })
    }
  }
})
