/* Generated by exb-i18n-kit. Hand edits are kept as manual translations on the next sync. */
System.register([], function (e) {
  return {
    execute: function () {
      e({
        selectMapWidget: "选择地图微件",
        settings: "设置",
        showScale: "显示缩放",
        showZoom: "显示缩放",
        uiPictometryConfiguration: "几何配置",
        uiPictometryBaseUrl: "图形基址",
        uiEnterTheFullUrlIncludingAspx: "输入包括.aspx文件在内的完整 URL",
        uiButtonVisibility: "按钮可见度",
        uiHelp: "帮助",
        uiShowHelpGuide: "显示帮助指南",
        uiShowTheQuestionMarkButtonThat: "显示打开部件帮助指南的问题标记按钮",
        showPictometryButton: "显示比对按钮",
        showGoogleStreetViewButton: "显示 Google 街景按钮",
        showGoogleMaps3dButton: "显示 Google 地图 3D 按钮",
        showBingSatelliteButton: "显示 Bing 卫星按钮",
        showBingStreetsideButton: "显示边街按钮",
        showCopyCoordinatesButton: "显示复制坐标按钮"
      })
    }
  }
})
